apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lb-proxy-controller.fullname" . }}
  labels:
    {{- include "lb-proxy-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lb-proxy-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lb-proxy-controller.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "lb-proxy-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: nginx-init
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}-alpine"
          command:
              - sh
              - -c
          args:
              - 'cp -r /etc/nginx/* /opt/nginx-config/ && ls /opt/nginx-config'
         
          volumeMounts:
            - name: nginx-config
              mountPath: /opt/nginx-config
      containers:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}-alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
        - name: controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.controller }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LB_NGINX_NS
              value: {{ .Release.Namespace }}
            - name: LB_NGINX_SELECTOR
              value: {{ include "lb-proxy-controller.selectorOneLine" . | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /opt/nginx-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: nginx-config
          emptyDir: {}
