apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-lb
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - list
  - get
  - create
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - get
